version: "3.1"
services:
    mongo-express:
        image: mongo-express
        ports:
        - 8081:8081
        networks:
        - network
        environment:
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_BASICAUTH_USERNAME: root
            ME_CONFIG_BASICAUTH_PASSWORD: pass
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: pass
        links:
        - mongo        
        depends_on:
        - mongo       
    mongo:
        image: mongo
        ports:
        - "27017:27017"
        networks:
        - network
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: pass
            MONGO_INITDB_DATABASE: test
        volumes:
        - ./data:/data/db
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
networks:
    network:
        driver: bridge
            